[package]
name = "cs-keys"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
thiserror = { workspace = true }
cs-crypto = { path = "../cs-crypto" }
base64 = "0.22"
serde = { workspace = true }
postcard = { version = "1", features = ["alloc"] }

[features]
default = []
keyring = ["dep:keyring"]

[dependencies.keyring]
version = "3"
optional = true
